config/routes.rb
Rails.application.routes.draw do
  get'product_mutation_history/' => 'product_mutation_history#index'
  get'product_mutation_history/:product_detail_id' => 'product_mutation_history#index'
  namespace :store_admin_reports do
    resources :sales_per_m_classes, only: [:index]
    resources :sales_realizations, only: [:index]
    resources :revenues, only: [:index]
    resources :discounts, only: [:index]
    resources :omsets, only: [:index]
    resources :eods, only: [:index]
  end
  namespace :warehouse_admin_reports do
    resources :surat_jalans, only: [:index]
    resources :global_pencocokan_returs, only: [:index]
  end
  resources :kedatangan_barang, only: [:index] do
    get :export
  end
  resources :report_transferan, only: [:index] do
    get :export
  end
  namespace :finance_reports do
    resources :bank_outs, only: [:index, :show] do
      collection do
        get :export
      end
    end
    resources :cash_outs, only: [:index] do
      collection do
        get :export
      end
    end
    resources :global_finances, only: :index do
      collection do
        get :export
      end
    end
    resources :journal_memos, only: :index do
      collection do
        get :brands_per_supplier
        get :export
      end
    end
    resources :account_payables, only: :index do
      collection do
        get :export
      end
    end
    resources :sisa_hutang_dagang, only: :index do
      collection do
        get :export
      end
    end
    resources :report_azzurra, only: :index do
      collection do
        get :export
      end
    end
    resources :store_cashs, only: :index do
      collection do
        get :export
      end
    end
    resources :receivables, only: :index do
      collection do
        get :export
      end
    end
    resources :repayments, only: :index do
      collection do
        get :export
      end
    end
    resources :denominations, only: :index do
      collection do
        get :export
      end
    end
  end

  resources :selling_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end

  namespace :finances do
    resources :cash_outs, only: [:new, :create, :show, :edit, :update]
    resources :petty_cashes
    resources :sod_eods do
      collection do
        get :add_input
      end
    end
    resources :monthly_payments
    resources :account_payables do
      member do
        get :print_to_pdf
      end
    end
    resources :account_receivables
    resources :forecasts do
      resources :monthly_forecasts
    end
    resources :budgetings
  end
  get 'get_branches' => 'finances/petty_cashes#get_branches', :as => :get_branches

  namespace :finances do
    resources :petty_cash
  end

  resources :product_details
  resources :transaction_histories do
    collection do
      get :search
    end
  end

  resources :ar_vouchers do
    collection do
      get :add_payment
    end
  end

  resources :products do
    collection do
      get :stock
      get :add_branch
      get :add_m_class
      get :autocomplete_goods_barcode
      get :mclass_per_department
      get :transaction_history
      post :import
    end
  end

  resources :change_barcodes

  resources :edc_bank_accounts do
    collection do
      post :import
    end
  end
  resources :edc_machines do
    collection do
      post :import
    end
  end
  resources :head_offices do
    collection do
      get :autocomplete_head_office_office_name
      post :import
    end
  end

  resources :branches do
    collection do
      get :autocomplete_branch_office_name
      post :import
    end
  end
  resources :vouchers
  resources :promos
  resources :stock_transfers do
    collection do
      get :search
      get :autocomplete_stock_transfer_name
      get :add_brand
      get :add_product
      get :get_last_number
    end
    member do
      get :print_to_pdf
    end
  end

  resources :units do
    collection do
      get :autocomplete_unit_name
      post :import
    end
  end

  resources :report_finances do
    collection do
      get :pembayaran_per_bulan
    end
  end

  resources :m_classes do
    collection do
      get :autocomplete_m_class_name
      get :add_sub_m_class
      post :import
    end
  end

  resources :product_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end

  resources :product_transfer_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end
  resources :member_types do
    collection do
      get :autocomplete_member_type_name
      post :import
    end
  end
  resources :catalogs do
    collection do
      get :autocomplete_catalog_name
      post :import
    end
  end
  resources :petty_cash_types do
    collection do
      get :autocomplete_petty_cash_type_name
      post :import
    end
  end
  resources :colours do
    collection do
      get :autocomplete_colour_name
      post :import
    end
  end
  resources :cashbacks do
    collection do
      post :import
    end
  end
  resources :member_levels do
    collection do
      get :autocomplete_member_level_description
      post :import
    end
  end
  resources :to_do_lists do
    collection do
      post :import
    end
  end
  resources :promotions do
    collection do
      get :search
      get :autocomplete_promotion_name
      get :add_prize_list
      get :add_promo_item_list
      get :search_product_manual
      get :search_in_modal
      get :get_product
    end
  end

  resources :branch_prices

  resources :stock_opnames do
    collection do
      get :get_quantity_data
      get :start_stock_opname_data
      get :end_stock_opname_data
      get :select_stock_opname_data
    end
  end

  resources :stock_opname_details do
    collection do
      post :import
    end
  end

  resources :members do
    collection do
      get :search
      get :discount
      post :create_member_discount
      post :import
      get '/edit_member_discount/:id' => 'members#edit_member_discount', as: :edit_member_discount
      put '/update_member_discount/:id' => 'members#update_member_discount', as: :update_member_discount
      delete '/delete_member_discount/:id' => 'members#delete_member_discount', as: :delete_member_discount
      put '/expired/:id' => 'members#expire', as: :expire
      get '/setting_point' => 'members#setting_point', as: :setting_point
      post 'create_setting_point' => 'members#create_setting_point', as: :create_setting_point
    end
  end

  resources :colours do
    collection do
      get :search
      get :autocomplete_colour_name
    end
  end

  resources :out_stocks do
    collection do
      get :search
      get :autocomplete_out_stock_name
    end
  end

  resources :min_stocks do
    collection do
      get :search
      get :autocomplete_min_stock_name
    end
  end

  resources :price_histories do
    collection do
      get :search
    end
  end

  resources :good_transfers do
    member do
      get :print_to_pdf
    end
    collection do
      get :search
      get :autocomplete_good_transfer_code
      get :get_product
      get :add_brand
      get :add_product
      get :get_last_number
    end
  end

  resources :departments do
    collection do
      get :search
      get :autocomplete_department_name
      get :departments_per_supplier
      post :import
      get :departments_list
    end
  end

  resources :brands do
    collection do
      get :search
      get :autocomplete_brand_name
      post :import
      get :brands_per_supplier
      get :generate_data_brand
    end
  end

  resources :suppliers do
    collection do
      get :get_number
      get :search
      get :autocomplete_supplier_name
      get :autocomplete_supplier_code
      post :import
      get :add_contact
      get :add_bank_account
    end
  end

  resources :sizes do
    collection do
      get :search
      get :autocomplete_size_name
      get :generate_details
      post :import
    end
  end

  resources :types do
    collection do
      get :search
      get :autocomplete_type_name
      get 'detail_sub_type/:id' => "types#detail_sub_type", as: :detail_sub_type
      get 'new_sub_type/:id' => "types#new_sub_type", as: :new_sub_type
    end
  end

  devise_for :users
  resources :users do
    collection do
      get :autocomplete_name
    end
  end
  resources :user_profiles do

  end

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update

    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles

  resources :approvals

  resources :asset_assignments do
    collection do
      post :return
    end
  end

  resources :recruitments

  resources :visions, only: [:index, :show] do
    collection do
      post :setup
      get :visi_misi
    end
  end

  resources :misions, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :cultures, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :code_of_conducts, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :values, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :holidays

  resources :personal_datas

  resources :holiday_types do
    collection do
      put :update_holiday_type
      get :search
    end
  end

  resources :shifts

app/models/branch.rb
class Branch < Office
  has_many :good_transfers
  has_many :product_details, class_name: 'ProductDetail', primary_key: 'id', foreign_key: 'warehouse_id'
  belongs_to :head_office

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:destroy]
  autocomplete :branch, :office_name
  before_filter :can_view_branch, only: [:index, :show]
  before_filter :can_manage_branch, only: [:new, :create, :edit, :update, :destroy]

  def destroy
    @branch = Branch.find(params[:id])
    if @branch.check_transaction && @branch.destroy
      flash[:error] = nil
      flash[:notice] = "Successfully delete branch"
    else
      flash[:notice] = nil
      flash[:error] = "Can't delete branch. data in use"
    end
    get_paginated_branches
    respond_to do |format|
      format.js
      if(params[:a] == "a")
        format.csv { send_data Branch.all.to_csv2 }
      else
        format.csv { send_data Branch.all.to_csv }
      end
    end
  end

  def import
    import_result = Branch.import(params[:file], 'Branch')
    if params[:file].present?
      if import_result[:error] == 1
        flash[:error] = import_result[:message]
      else
        flash[:notice] = import_result[:message]
      end
    else
      flash[:error] = "Please attach CSV File"
    end
    redirect_to branches_path
  end

  # POST /suppliers
  # POST /suppliers.json
  def update
    @branch = Branch.find(params[:id])
    office_departments = @branch.office_departments.map(&:id).join(', ')
    respond_to do |format|
      if @branch.update_attributes(branch_params.merge(contact_person: (User.find_by_username(params[:username]).id rescue nil)))
        @branch.office_departments.where("id IN (#{office_departments})").delete_all if office_departments.present?
        flash[:notice] = t(:successfully_updated)
      else
        @head_offices = HeadOffice.all
        @users = User.all.map{|user|[user.username, user.id]}
        load_departments
        flash[:error] = @branch.errors.full_messages.join('<br/>')
      end
      format.js
    end
  end

  def edit
    @branch = Branch.find(params[:id])
    @head_offices = HeadOffice.all
    @users = User.all.map{|user|[user.username, user.id]}
    load_departments
  end

  def new
    @branch = Branch.new
    @users = User.joins(:role).limit(7).map{|user|[user.username, user.id]}
    @head_offices = HeadOffice.all
    load_departments
    respond_to do |format|
      format.html
    end
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @branch = Branch.new(branch_params.merge(contact_person: (User.find_by_username(params[:username]).id rescue nil)))
    @head_offices = HeadOffice.all
    @users = User.joins(:role).limit(7).map{|user|[user.username, user.id]}
    respond_to do |format|
      if @branch.save
        flash[:notice] = t(:successfully_created)
      else
        @head_offices = HeadOffice.all
        @users = User.joins(:role).limit(7).map{|user|[user.username, user.id]}
        load_departments
        flash.now[:error] = @branch.errors.full_messages.join('<br/>')
      end
      format.js
    end
  end

  def index
    get_paginated_branches
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xls {
        filename = "Cabang_#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}.xls"
        send_data(@branches.to_xls, :type => "text/xls; charset=utf-8; header=present", :filename => filename)
      }
      format.json{
        render json: @branches.map{|branch|
          sales_sum = Sale.where("store_id=#{branch.id}").map(&:total_price).compact.sum
          target_sec2015 = 10000000
          {
            office_name: branch.description, lat: branch.lat, long: branch.long, achievement: [(sales_sum/target_sec2015*100).round(2), 100].min, target_sec2015: target_sec2015,
              secsales: sales_sum
          }
        }.to_json
      }
    end
  end

  def show
    @branch = Branch.find(params[:id])
    @departments = @branch.departments
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  private
  def branch_params
    params.require(:branch).permit(
      :office_name, :description, :warehouse, :contact_person, :phone_number, :fax_number, :mobile_phone, :address, :short_address, :head_office_id, :lat, :long,
      office_departments_attributes: [:department_id]
    )
  end

  def can_view_branch
    not_authorized unless current_user.can_view_branch?
  end

  def can_manage_branch
    not_authorized unless current_user.can_manage_branch?
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_branch_list.html.erb
<% @branches.each_with_index do |branch, i| %>
  <tr>
    <td class="hidden-phone"><%= params[:page] ? (params[:page].to_i*10+i-9) : i+1 %></td>
    <td><%= link_to branch.office_name, branch_path(branch), class: 'blue' %></td>
    <td class="hidden-phone"><%= branch.head_office_name %></td>
    <td class="hidden-phone"><%= branch.description %></td>
    <td class="hidden-phone"><%= branch.warehouse %></td>
    <td class="hidden-phone"><%= branch.username %></td>
    <td class="hidden-phone"><%= branch.phone_number %></td>
    <td class="hidden-phone"><%= branch.fax_number %></td>
    <td class="hidden-phone"><%= branch.mobile_phone %></td>
    <td class="hidden-phone"><%= branch.address %></td>
    <% if current_user.can_manage_branch? %>
    <td class="nowrap">
      <%= link_to raw("<i class='fa fa-pencil'></i>"), edit_branch_path(branch), class: "btn btn-primary btn-xs custom-edit-btn" %>
      <%= link_to raw("<i class='fa fa-trash-o'></i>"), 'javascript:void(0)', onclick: "delete_one(#{branch.id}, 'branches')", class: "btn btn-danger btn-xs custom-edit-btn" %>
    </td>
    <% end %>
  </tr>
<% end %>
<tr>
  <td colspan=11><!-- start pagination -->
    <div class="dataTables_paginate paging_simple_numbers" id="dt_basic_paginate">
      <%= pagination_links(@branches, options = {}) %>
    </div>
  </td>
</tr>

app/views/branches/create.js.erb
<% if @branch.errors.full_messages.present? %>
  $("#notification").html("<%= j(render 'layouts/errors') %>");
  window.scrollTo(0, 0);
<% else %>
  window.location = '/branches'
<% end %>

app/views/branches/destroy.js.erb
$("#branch-list").html("<%= j(render 'branch_list') %>");
$('#notice_template').html("<%= j(render 'layouts/notice') %>")
paging()

app/views/branches/edit.html.erb
<%= render partial: 'form', locals: {label: 'Edit'} %>

app/views/branches/index.html.erb
<link rel="stylesheet" href="/css/jquery-ui-1.11.4.css">
<script src="/js/jquery-1.10.2.js"></script>
<script src="/js/jquery-ui-1.11.4.js"></script>
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Data Master</li><li>Cabang</li><li>List</li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <section id="widget-grid" class=""><!-- widget grid -->
    <div id='notice_template'><%= render 'layouts/notice' %></div>
    <div class="row"><!-- row -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><!-- NEW WIDGET START -->
        <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-1" data-widget-editbutton="false"><!-- Widget ID (each widget will need unique ID)-->
          <h2 style="color:#BF1E2D; margin-top:-5px;"><i class="fa fa-list-ul"></i> <%= t(:branch_list) %></h2> <!-- header content -->
          <div><!-- widget div-->
          <% if current_user.can_manage_branch? %>
            <div class="widget-body no-padding"><!-- widget content -->
              <%= link_to new_branch_url, :class => "btn btn-labeled btn-primary edit-btn-primary" do %>
                <span class="btn-label"><i class="glyphicon glyphicon-plus"></i></span><%= t(:add_branch) %>
              <% end %>
              <!--
              <ul id="myTab1" class="nav nav-tabs" style='margin: 20px 0 6px 6px; float: left'>
                <li class="dropdown">
                  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i></button>
                  <ul class="dropdown-menu">
                    <%# if current_user.can_manage_branch? %>
                    <li data-toggle="modal" data-target="#myModal" style='cursor: pointer'><a>Import dari CSV</a></li>
                    <%# end %>
                  </ul>
                </li>
              </ul>
              -->
            </div>
            <% end %>
            <table class="table table-striped table-bordered" width="100%">
              <thead>
                <tr>
                  <th>No</th>
                  <th>
                    Nama Cabang <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-asc', class: 'sorting' %>
                  </th>
                  <th>
                    Nama HO <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'office_name-asc', class: 'sorting' %>
                  </th>
                  <th>
                    Deskripsi <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'description-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'description-asc', class: 'sorting' %>
                  </th>
                  <th>
                    Gudang <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'warehouse-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'warehouse-asc', class: 'sorting' %>
                  </th>
                  <th class='nowrap'>
                    Penanggung Jawab (CP) <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'contact_person-desc', class: 'sorting hide' %>
                  <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'contact_person-asc', class: 'sorting' %>
                </th>
                <th>
                  No Tlp <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'phone_number-desc', class: 'sorting hide' %>
                  <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'phone_number-asc', class: 'sorting' %>
                  </th>
                  <th>
                    No Fax <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'fax_number-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'fax_number-asc', class: 'sorting' %>
                  </th>
                  <th>
                    No HP <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'mobile_phone-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'mobile_phone-asc', class: 'sorting' %>
                  </th>
                  <th>
                    Alamat<%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'address-desc', class: 'sorting hide' %>
                    <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'address-asc', class: 'sorting' %>
                  </th>
                  <% if current_user.can_manage_branch? %>
                  <th>Aksi</th>
                  <% end %>
                </tr>
                <tr>
                  <th></th>
                  <th class="hasinput"><%= text_field_tag :office_name, params[:office_name], class: 'form-control search', name: 'offices.office_name' %></th>
                  <th class="hasinput"><%= text_field_tag :head_office_name, params[:head_office_name], class: 'form-control search', name: 'head_offices.office_name' %></th>
                  <th class="hasinput"><%= text_field_tag :description, params[:description], class: 'form-control search', name: 'offices.description' %></th>
                  <th class="hasinput"><%= text_field_tag :warehouse, params[:warehouse], class: 'form-control search', name: 'offices.warehouse' %></th>
                  <th class="hasinput"><%= text_field_tag :contact_person, params[:contact_person], class: 'form-control search', name: 'username' %></th>
                  <th class="hasinput"><%= text_field_tag :phone_number, params[:phone_number], class: 'form-control search', name: 'offices.phone_number' %></th>
                  <th class="hasinput"><%= text_field_tag :fax_number, params[:fax_number], class: 'form-control search', name: 'offices.fax_number' %></th>
                  <th class="hasinput"><%= text_field_tag :mobile_phone, params[:mobile_phone], class: 'form-control search', name: 'offices.mobile_phone' %></th>
                  <th class="hasinput"><%= text_field_tag :address, params[:address], class: 'form-control search', name: 'offices.address' %></th>
                  <% if current_user.can_manage_branch? %>
                  <th></th>
                  <% end %>
                </tr>
              </thead>
              <tbody id='branch-list'><%= render 'branch_list' %></tbody>
            </table>
          </div><!-- end widget -->
        </div><!-- end widget div -->
      </article><!-- WIDGET END -->
    </div><!-- end row -->
  </section><!-- end widget grid -->
</div><!-- end row -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import Cabang</h4>
      </div>
      <%= form_tag import_branches_path(:id => params[:id]), multipart: true do %>
        <div class="modal-body">
          <%= file_field_tag :file, accept: ".csv", onchange: "checkfile(this);" %>
        </div>
        <div class="modal-footer">
          <%#= link_to "Download Template", head_offices_path(format: "csv", :a => "a"), :class => "btn btn-success" %>
          <%= submit_tag "Import", :class => "btn btn-primary", :id => 'commit'%>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('#commit').bind("click",function(){ 
    if(!$('#file').val()){
      alert("File belum dipilih");
      return false;
    }
  }); 
  window.reset = function (e) {
    e.wrap('<form>').closest('form').get(0).reset();
    e.unwrap();
  }
});
function checkfile(sender) {
    var validExts = new Array(".csv");
    var fileExt = sender.value;
    fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
    if (validExts.indexOf(fileExt) < 0) {
      alert("File ini bukan .csv");
      reset($("#file"));
      return false;
    }
    else return true;
};
</script>

app/views/branches/index.js.erb
$("#branch-list").html("<%= j(render 'branch_list') %>");
paging()

app/views/branches/new.html.erb
<%= render partial: 'form', locals: {label: 'Tambah'} %>

app/views/branches/show.html.erb
<script src="/js/jquery-2.1.1.min.js"></script><!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<div id="ribbon"><!-- RIBBON -->
  <ol class="breadcrumb"><!-- breadcrumb -->
    <li>Data Master</li><li>Branch</li><li><%= @branch.office_name %></li>
  </ol><!-- end breadcrumb -->
</div><!-- END RIBBON -->
<div id="content"><!-- MAIN CONTENT -->
  <%= render 'layouts/errors' %>
  <div class="row">
    <article class="col-sm-12 col-md-12"><!-- NEW COL START -->
      <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
        <header id="header-supplier">
          <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
          <h2><%= @branch.office_name %></h2>
        </header>
        <div><!-- widget div-->
          <div class="widget-body no-padding"><!-- widget content -->
            <%= form_for @branch, html: {class: "smart-form", id: "form-update-verify"} do |f| %>
              <fieldset> <!-- tambah supplier -->
                <div class="row">
                  <section class="col col-md-6">
                    <section class="form-group">
                      <label class="col-md-4 label">Nama Cabang</label>
                      <label class="col-md-8 input custom-input-box"><%= @branch.office_name %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Deskripsi</label>
                      <label class="col-md-8 textarea custom-input-box"><%= @branch.description %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Gudang</label>
                      <label class="col-md-8 input custom-input-box"><%= @branch.warehouse %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Penanggung Jawab (CP)</label>
                      <label class="col-md-8 input custom-input-box">
                        <%= @branch.user.first_name rescue '' %> <%= @branch.user.last_name rescue '' %>
                      </label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-4 label">Departement</label>
                      <label class="col-md-8 label">
                      <% @departments.each_with_index do |depart, i| %>
                          <%= depart.department.name %> <br> 
                        <% end %>
                        </label>
                    </section><br>
                  </section>
                  <section class="col col-md-6">
                    <section class="form-group">
                      <label class="col-md-2 label">No Tlp</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.phone_number %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">No Fax</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.fax_number %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">No HP</label>
                      <label class="col-md-10 input custom-input-box"><%= @branch.mobile_phone %></label>
                    </section><br>
                    <section class="form-group">
                      <label class="col-md-2 label">Alamat</label>
                      <label class="col-md-10 textarea custom-input-box"><%= @branch.address %></label>
                    </section><br>
                  </section><br>
                </div>
              </fieldset>
              <footer>
                <button type="button" class="btn btn-default" onclick="window.history.back();">Back</button>
              </footer>
            <% end %>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>

app/views/branches/update.js.erb
<% if @branch.errors.full_messages.present? %>
  $("#notification").html("<%= j(render 'layouts/errors') %>");
  window.scrollTo(0, 0);
<% else %>
  window.location = '/branches'
<% end %>