config/routes.rb
      post 'create_setting_point' => 'members#create_setting_point', as: :create_setting_point
    end
  end

  resources :colours do
    collection do
      get :search
      get :autocomplete_colour_name
    end
  end

  resources :out_stocks do
    collection do
      get :search
      get :autocomplete_out_stock_name
    end
  end

  resources :min_stocks do
    collection do
      get :search
      get :autocomplete_min_stock_name
    end
  end

  resources :price_histories do
    collection do
      get :search
    end
  end

  resources :good_transfers do
    member do
      get :print_to_pdf
    end
    collection do
      get :search
      get :autocomplete_good_transfer_code
      get :get_product
      get :add_brand
      get :add_product
      get :get_last_number
    end
  end

  resources :departments do
    collection do
      get :search
      get :autocomplete_department_name
      get :departments_per_supplier
      post :import
      get :departments_list
    end
  end

  resources :brands do
    collection do
      get :search
      get :autocomplete_brand_name
      post :import
      get :brands_per_supplier
      get :generate_data_brand
    end
  end

  resources :suppliers do
    collection do
      get :get_number
      get :search
      get :autocomplete_supplier_name
      get :autocomplete_supplier_code
      post :import
      get :add_contact
      get :add_bank_account
    end
  end

  resources :sizes do
    collection do
      get :search
      get :autocomplete_size_name
      get :generate_details
      post :import
    end
  end

  resources :types do
    collection do
      get :search
      get :autocomplete_type_name
      get 'detail_sub_type/:id' => "types#detail_sub_type", as: :detail_sub_type
      get 'new_sub_type/:id' => "types#new_sub_type", as: :new_sub_type
    end
  end

  devise_for :users
  resources :users do
    collection do
      get :autocomplete_name
    end
  end
  resources :user_profiles do

  end

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update

    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles

  resources :approvals

  resources :asset_assignments do
    collection do
      post :return
    end
  end

  resources :recruitments

  resources :visions, only: [:index, :show] do
    collection do
      post :setup
      get :visi_misi
    end
  end

  resources :misions, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :cultures, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :code_of_conducts, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :values, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :holidays

  resources :personal_datas

  resources :holiday_types do
    collection do
      put :update_holiday_type
      get :search
    end
  end

  resources :shifts

  resources :knowledges do
    collection do
    	get :autocomplete_name
      get :knowledge_new
      get :search
      get :knowledge_show
      get :knowledge_new
      post :knowledge_create
      delete :knowledge_destroy
      get :knowledge_edit
      patch :knowledge_update
      put :knowledge_update
      post :dropzone
      get :dropzone

    end
  end

  resources :blast_messages do
    collection do
      get :autocomplete_organization_name
      get :autocomplete_employee_name
    end
  end

  resources :components do
  collection do
      put :update_component
      post :import
    end
  end
  resources :selecteds

  resources :knowledges

  resources :knowledge_details

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :employee_histories do
    collection do
      put :update_employee_histories
    end
  end

  resources :employee_working_datas do
    collection do
      put :update_employee_working_data
      post :import
    end
  end

  resources :salaries do
    collection do
      put :update_salary
      post :import
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

  resources :employees do
    collection do
end
end

  resources :components

  resources :families do
    collection do
      put :update_family
    end
  end

  resources :position_details do
    collection do
      put :update_position_detail
      post :import
    end
  end

  resources :contracts do
    collection do
      put :update_contract
    end
  end

  resources :training_histories do
    collection do
      put :update_training_history
    end
  end

  resources :language_skills do
    collection do
      put :update_language_skill
    end
  end

  resources :skills do
    collection do
      put :update_skill
    end
  end

resources :violation_details do
    collection do
      put :update_violation_detail
    end
  end

  resources :salaries do
    collection do
      put :update_salary
    end
  end

  resources :member_levels

  namespace :api do
    resources :members, :only => [:create]
    resources :transactions, :only => [:create]
    resources :desktop_api, only: [:index] do
      collection do
        get :vouchers_list
        get :pos_machines_list
        get :voucher_details_list
        get :product_size_list
        get :vouchers_list
        get :prizes_list
        get :promo_items_list
        get :member_balance_mutations_list
        get :member_point_mutations_list
        get :cashback
        post :lock_member
        get :use_promo
        get :product_promo_discounts
        get :discount_histories
        get :product_discount
        get :member_levels
        get :users
        get :promotions_list
        get :edc_bank_account_list
        get :product_detail_list
        get :price_per_branch
        get :department_list
        get :product_stock
        get :size_details_list
        get :size_list
        get :m_class_list
        get :supplier_list
        get :product_list
        get :gift_list
        get :members
        get :voucher
        get :roles
        get :voucher_details
        post :transaction
        post :create_sod_eod
        post :update_sod_eod
        post :create_member
        post :create_session
        post :create_member_balance
        post :create_member_point
        post :create_goods_request
        post :create_goods_movement
        post :create_voucher
        post :voucher_to_used
        post :create_sales
        post :create_exchange_order
        post :create_refund_order
        post :sync_ptb
        post :active_and_unused_vouchers
        get :colours_list
        get :brands_list
        get :item_request_list
        post :process_employee
        get :get_employees
        get :warehouse_list
        get :goods_detail_list
        get :member_list
        get :bank_list
        get :goods_sizes_list
        get :unit_list
        get :product_list_new
        get :branch_list
      end
    end
    devise_for :users, path_prefix: 'api', controllers: {sessions: "api/sessions"}
  end

  resources :external_work_experiences do
    collection do
      put :update_external_work_experience
    end
  end

  resources :internal_work_experiences do
    collection do
      put :update_internal_work_experience
    end
  end

  resources :history_of_organizations do
    collection do
      put :update_history_of_organization
    end
  end

  resources :certifications do
    collection do
      put :update_certification
    end
  end

  resources :performances do
    collection do
      put :update_performance
    end
  end

  resources :po_histories

  resources :employees do
    collection do
      get :employee_working_datas
      get :new_employee_working_datas
      post :create_employee_working_datas
       get :employee_histories
      get :new_employee_histories
      post :create_employee_histories
      get :family_details
      get :new_family_details
      post :create_family_details
      get :new_personal_data
      post :create_personal_data
    end
  end

  resources :divisions

  resources :absences

  resources :appraisals do
    collection do
      get :get_value
    end
  end

  resources :leave_requests

  resources :overtime_requests

  resources :overtime_requests do
    collection do
      put :update_overtime_request
      post :import
    end
  end

  resources :interview_results do
    member do
      patch :update_status
      put :update_status
    end
  end

  resources :test_results do
    member do
      patch :update_status
      put :update_status
    end
  end

  resources :approval_levels do
    collection do
      get :autocomplete_employee_name
    end
  end

  resources :code_of_conducts, only: [:index] do
    collection do
      post :index
      post :setup
    end
  end
  resources :media_socials

  root 'dashboards#index'
  get 'dashboards/line_chart'
  get 'dashboards/daily_sales'
  post 'dashboards/update_todolist'

resources :surveys do
    collection do
      post :filter
      get :filter

      post :get_view
      get :reload
      post :reorder
      get :question_list
      get "preview/:id" => "surveys#preview", as: :preview
      get :add_row
      get :remove_row
      get :question_detail
      get :question_page
      get :reset_session

      post :set_question
      get :edit_question
      get :add_question
      get "manage_question/:section" => "surveys#manage_question", as: :manage_question

app/views/admin/knowledges/_form.html.erb
<%= tinymce_assets %>
<div class="container-fluid">
  <ul class="breadcrumb">
    <li><p>YOU ARE HERE</p></li> 
    <li><a href="">Knowledge Management</a></li>
    <li><a href="#" class="active">New</a></li>
  </ul>
</div>
<div class="page-title">
  <i class="fa fa-envelope"></i>
  <h3>Knowledge <span class="semi-bold">Management</span></h3>
</div>
  <div class="grid simple">
    <%= form_for @knowledge, url: knowledges_path, html: { multipart: true } do |f| %>

        <div class="grid-title no-border"></div>
            <div class="grid-body no-border">
                <div class="gen-form" action="">
                 
                  <div class="form-group row">
                        <label class="form-label col-sm-12"><strong>Article Name</strong></label>
                        <div class="controls col-sm-12">             
                            <%= f.text_field :article_name, :class => "full-width", :placeholder => "Article Name" %>
                        </div>
                     </div>
                     
                     <div class="form-group row">
                      <div class="form-label col-sm-12">
                            <label class="form-label"><strong>Categories</strong></label>
                            <span class="help">e.g. "Business", "Technical"</span>
                        </div>
                        <div class="controls col-sm-12">
                            <% if params[:action] == 'edit' %>
                              <%= f.autocomplete_field :category_id, autocomplete_name_knowledges_url, 'data-delimiter' => ',', :multiple => true, class: "autocomplete-field-input", placeholder: "Categories", value: (f.object.knowledge_receivers.present? ? f.object.knowledge_receivers.map{ |receiver| receiver.category.name }.join(', ') : params[:knowledge][:category_id]) %> 
                            <% else %>
                                <%= f.autocomplete_field :category_id, autocomplete_name_knowledges_url, 'data-delimiter' => ',', :multiple => true, class: "autocomplete-field-input", placeholder: "Categories" %> 
                            <% end %>
                                     
                        </div>
                     </div>
                    </div>
<!-- =======
      <%= raw @knowledge.errors.full_messages.join('</br>') if @knowledge.errors.full_messages.present? %>
      <% knowledge_receivers = f.object.knowledge_receivers %>
      <div class="grid-title no-border"></div>
        <div class="grid-body no-border">
          <div class="gen-form" action="">
            <div class="form-group row">
              <label class="form-label col-sm-12"><strong>Article Name</strong></label>
              <div class="controls col-sm-12">
                <%= f.text_field :article_name, :class => "full-width", :placeholder => "Article Name" %>
              </div>
             </div>
             <div class="form-group row">
               <div class="form-label col-sm-12">
                 <label class="form-label"><strong>Categories</strong></label>
                 <span class="help">e.g. "Business", "Technical"</span>
               </div>
                <div class="controls col-sm-12">
                  <%= f.autocomplete_field :category_id, autocomplete_name_knowledges_url, 'data-delimiter' => ',', :multiple => true, class: "autocomplete-field-input",
                    placeholder: "Categories",
                    value: knowledge_receivers.present? ? (knowledge_receivers.map{ |receiver| receiver.category.name }).join(",") : (params[:knowledge][:category_id] rescue '') %>
>>>>>>> 971d3b8cfaab917baa11e6fe7b6dd1f66d1302f6 -->
                </div>
             </div>
      
      <div class="col-sm-12"> 
        <div class="grid simple">
          <%= f.text_area :content,  :id => "text-editor", :placeholder => "Enter text  ...", :class => "form-control tinymce", :rows => "10" %>
                    </div>
                    </div>
                    

                    <!-- <div action="#" class="dropzone no-margin">
                      <div class="fallback">
                        <%= f.file_field :image %><br>                   
                        <%= f.submit "Submit" %>
                      </div>
                    </div> --> 

                      <div class="col-sm-3">
                              <div class="profile-user del-mrg">
                                    <a class="opt-profile change tip btn-upload" data-toggle="tooltip" data-placement="top" data-original-title="Upload"><i class="fa fa-upload" onclick="$('#knowledge_image').click();"></i></a>
                                    <%= f.file_field :image, class: "opt-profile change tip hidden fa fa-upload", :data => {toggle: 'tooltip', placement: 'top', 'original-title' => 'Upload'}, placeholder: "Upload your image", :onchange =>"readURL(this);"%>
                                      
                                  
                                        <img id="img_prev" src="/assets/gallery/Actions-insert-image-icon.png"/>
                                  
                                </div>
                            </div>

      
            <div class="form-actions">  
                <div class="pull-right">
                  <!-- <button type="button" class="btn btn-cons"> Preview </button> -->
                  <%= submit_tag 'Preview', class: "btn btn-success btn-cons", :name => 'preview_button' %>
                  <%= button_tag class: "btn btn-success btn-cons", type: "submit", name: "commit", value: "publish" do %>
                    Save and Publish <i class="fa fa-send"></i>
                  <% end %>
                  <%= button_tag class: "btn btn-success btn-cons", type: "submit", name: "commit", value: "save" do %>
                    Save
                  <% end %>
                </div>
            </div>
    <% end %>

  <script type="text/javascript">
    $('#select_send').change(function(){
      var value = $(this).val();
      if(value == 'emp'){
        $('#emp_text').show('fast');
      }else{
        $('#emp_text').hide('fast')
      }
    });
    </script>

<script type="text/javascript">
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#img_prev')
          .attr('src', e.target.result)
          .width(240)
          .height(250);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
</script>
<%= tinymce %>

app/views/admin/knowledges/edit.html.erb
<%= render 'form', :knowledge => @knowledge %>

app/views/admin/knowledges/index.html.erb
<div class="container-fluid">
    	<ul class="breadcrumb">
            <li><p>YOU ARE HERE</p></li> 
            <li><a href="#" class="active">Knowledge Management</a></li>
        </ul>
        
        <div class="page-title">	
        	<i class="fa fa-book"></i>
        	<h3>Knowledge - <span class="semi-bold">Management</span></h3>	
        </div>  
            <div class="grid simple">
           	  <div class="grid-title no-border"></div>
            	<div class="grid-body no-border">
					<div class="row toolbar-block">
                    	<div class="col-md-4">
                        	<div class="dataTables_filter" id="example3_filter">
                            	<div class="controls">
                                    <div class="input-group">
                                      <input type="text" class="form-control" placeholder="Search Record">
                                      <span class="input-group-addon ">
                                       	<i class="fa fa-search"></i>
                                      </span>
                                    </div>
                                  </div>
                            </div>
                        </div>

                        <div class="col-md-8">
                        	<div class="toolbar pull-right" id="toolbar_main">
                            	<div class="table-tools-actions">
                                  <%= link_to new_knowledge_path, id: "_new", class: "btn btn-success" do %>
                                         Add New <i class="fa fa-plus"></i>
                                <% end %>
                                    <div class="btn-group">
                                    	<button class="btn dropdown-toggle" data-toggle="dropdown"><span class="fa fa-gear"></span> <span class="caret"></span></button>
                                        <ul class="dropdown-menu right-edge">
                                          <li><a href="#">Action</a></li>
                                          <li><a href="#">Another action</a></li>
                                          <li><a href="#">Something else here</a></li>
                                          <li class="divider"></li>
                                          <li><a href="#">Separated link</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            
                
                        	<div class="toolbar pull-right hide" id="toolbar_upload">
                            	<div class="table-tools-actions">
                                	<button class="btn"><span class="fa fa-cloud-upload"></span> Upload</button>
                                    <div class="separator">&nbsp;</div>
                                </div>
                            </div>
                        	<div class="toolbar pull-right hide" id="toolbar_def">
                            	<div class="table-tools-actions">
                                	<button class="btn"><span class="fa fa-edit"></span> Edit</button> 
                                    <button class="btn" data-toggle="modal" data-target="#confirm_modal"><span class="fa fa-trash"></span> Remove</button> 
                                    <div class="separator">&nbsp;</div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                	<table class="table no-more-tables table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Article Name</th>
                                <th>Category</th>
                                <th>Statue</th>
                                <th class="text-center">Has been read</th>
                                <th class="text-center">Not read yet</th>
                            </tr>
                        </thead>
                        <tbody>
                           
                            <% @knowledges.each do |knowledge| %>
                              <tr>
                                <td><%= knowledge.article_name %></td>
                               <td></td>
                                <td><%= knowledge.status %></td>
                                </tr>
                             <% end %>
                              
                            
                        </tbody>
                    </table>
                    
                    <div class="row dataTables_wrapper">
                    	<div class="col-md-12">
                        	<div class="dataTables_paginate paging_bootstrap pagination">
                            	<ul>
                                    <li class="prev disabled"><a href="#"><i class="fa fa-chevron-left"></i></a></li>
                                    <li class="active"><a href="#">1</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li><li><a href="#">5</a></li><li class="next"><a href="#"><i class="fa fa-chevron-right"></i></a></li>
                                </ul>
                            </div>
                        	<div class="dataTables_info">Showing <b>1 to 10</b> of 57 entries</div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
  
</div>

    <script type="text/javascript">
        $('#text-editor').wysihtml5();
        $('#select_send').change(function(){
            var value = $(this).val();
            if(value == 'emp'){
                $('#emp_text').show('fast');
            }else{
                $('#emp_text').hide('fast')
            }
        });
    </script>

app/views/admin/knowledges/new.html.erb
<%= render 'form', :knowledge => @knowledge %>

app/views/admin/knowledges/show.html.erb
<div class="container-fluid">
    	<ul class="breadcrumb">
            <li><p>YOU ARE HERE</p></li> 
            <li><a href="konowledge_management.html">Knowledge Management</a></li>
            <li><a href="#" class="active">Detail</a></li>
        </ul>
        
        <div class="page-title">	
        	<i class="fa fa-envelope"></i>
        	<h3>Knowledge <span class="semi-bold">Management</span></h3>	
        </div>  
        <section class="row">
        	<div class="col-sm-9">
            	<div class="grid simple">
                  <div class="grid-title no-border">
                  	<h3 class="semi-bold p-l-5"> <%= @knowledge.article_name %>  </h3>  
                    <div class="tools">	
                    	<!-- <button href="#" class="btn"><i class="fa fa-pencil"></i> Edit</button> -->
                    	
                    	<%= link_to 'Edit', edit_knowledge_path(@knowledge), class: "fa fa-pencil" %> 
                    </div>  
                  </div>
                    <div class="grid-body no-border">
                      <form class="gen-form" action="">
                        <div class="form-group">                        
                            <div class="controls">						                    
                              <div class="controls">	
                               <% @knowledge.knowledge_receivers.each do |category| %>
                                    <tr>
                                        <span class="label label-info"><%= category.category.name %></td></span>
                                    </tr>
                                <% end %>					 
                                    <!-- <span class="label label-info">Company Rule</span>  -->
                               </div>
                            </div>
                         </div>
                    </form>
                        
                            <article>
                            
                                <%= simple_format (@knowledge.content)%>
                               
                            </article>

                      <!--   <br />
                        <form action="" class="dropzone no-margin">
                            <div class="dz-preview dz-processing dz-error dz-image-preview">  <div class="dz-details">    <div class="dz-filename"><span data-dz-name="">bd2x.jpg</span></div>    <div class="dz-size" data-dz-size=""><strong>92.7</strong> KB</div>    <img data-dz-thumbnail="" alt="bd2x.jpg" src="img/superbox-thumb-18.jpg">  </div>  </div>
                            <div class="dz-preview dz-processing dz-error dz-image-preview">  <div class="dz-details">    <div class="dz-filename"><span data-dz-name="">bd2x.jpg</span></div>    <div class="dz-size" data-dz-size=""><strong>92.7</strong> KB</div>    <img data-dz-thumbnail="" alt="bd2x.jpg" src="img/task.png">  </div>  </div>
                            <div class="dz-preview dz-processing dz-error dz-image-preview">  <div class="dz-details">    <div class="dz-filename"><span data-dz-name="">bd2x.jpg</span></div>    <div class="dz-size" data-dz-size=""><strong>92.7</strong> KB</div>    <img data-dz-thumbnail="" alt="bd2x.jpg" src="img/11.png">  </div>  </div>
                        </form> -->
                    </div>
                </div>
            </div>
            <aside class="col-sm-3 list">
            	<ul class="nav nav-pills" id="tab-4">
                    <li class="active"><a href="#read">Read By</a></li>
                    <li><a href="#not_read">Not Read Yet</a></li>
                  </ul>
				<div class="tab-content">
                	<div class="tab-pane active" id="read">
                    	<table class="table table-striped table-flip-scroll cf">
                        	<thead class="cf">
                                <tr>
                                    <th>#</th>
                                    <th>Employee Name</th>
                                </tr>
                            </thead>
                            <tbody>
                            	
                                <% @knowledge.knowledge_details.where(:status => true).each_with_index do |detail, i| %>
                                    <tr>
                                        <td><%= i + 1 %></td>

                                        <td><%= detail.user.name %></td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
					</div>
                    <div class="tab-pane" id="not_read">
                    	<table class="table table-striped table-flip-scroll cf">
                        	<thead class="cf">
                                <tr>
                                    <th>#</th>
                                    <th>Employee Name</th>
                                </tr>
                            </thead>
                            <tbody>
                            <% @knowledge.knowledge_details.where(:status => false).each_with_index do |detail, i| %>
                                    <tr>
                                        <td><%= i + 1 %></td>

                                        <td><%= detail.user.name %></td>
                                    </tr>
                                <% end %>
                            	<!-- <tr>
                                	<td>1</td>
                                    <td><a href="employee_detail.html"> Bee Gees </a></td>
                                </tr>
                                <tr>
                                	<td>2</td>
                                    <td><a href="employee_detail.html"> Steve Taylor </a></td>
                                </tr>
                                <tr>
                                	<td>3</td>
                                    <td><a href="employee_detail.html"> Eric Martin </a></td>
                                </tr>
                                <tr>
                                	<td>4</td>
                                    <td><a href="employee_detail.html"> Wiki Honduras </a></td>
                                </tr> -->
                            </tbody>
                        </table>
					</div>
                </div>
            </aside>
        </section>
    </div>