config/routes.rb
Rails.application.routes.draw do
  get'product_mutation_history/' => 'product_mutation_history#index'
  get'product_mutation_history/:product_detail_id' => 'product_mutation_history#index'
  namespace :store_admin_reports do
    resources :sales_per_m_classes, only: [:index]
    resources :sales_realizations, only: [:index]
    resources :revenues, only: [:index]
    resources :discounts, only: [:index]
    resources :omsets, only: [:index]
    resources :eods, only: [:index]
  end
  namespace :warehouse_admin_reports do
    resources :surat_jalans, only: [:index]
    resources :global_pencocokan_returs, only: [:index]
  end
  resources :kedatangan_barang, only: [:index] do
    get :export
  end
  resources :report_transferan, only: [:index] do
    get :export
  end
  namespace :finance_reports do
    resources :bank_outs, only: [:index, :show] do
      collection do
        get :export
      end
    end
    resources :cash_outs, only: [:index] do
      collection do
        get :export
      end
    end
    resources :global_finances, only: :index do
      collection do
        get :export
      end
    end
    resources :journal_memos, only: :index do
      collection do
        get :brands_per_supplier
        get :export
      end
    end
    resources :account_payables, only: :index do
      collection do
        get :export
      end
    end
    resources :sisa_hutang_dagang, only: :index do
      collection do
        get :export
      end
    end
    resources :report_azzurra, only: :index do
      collection do
        get :export
      end
    end
    resources :store_cashs, only: :index do
      collection do
        get :export
      end
    end
    resources :receivables, only: :index do
      collection do
        get :export
      end
    end
    resources :repayments, only: :index do
      collection do
        get :export
      end
    end
    resources :denominations, only: :index do
      collection do
        get :export
      end
    end
  end

  resources :selling_prices do
    collection do
      post :import
      get :search_product_manual
      get :search_in_modal
      get :fitur_filter
    end
  end

  namespace :finances do
    resources :cash_outs, only: [:new, :create, :show, :edit, :update]
    resources :petty_cashes
    resources :sod_eods do
      collection do
        get :add_input
      end
    end
    resources :monthly_payments
    resources :account_payables do
      member do
        get :print_to_pdf
      end
    end
    resources :account_receivables
    resources :forecasts do
      resources :monthly_forecasts
    end
    resources :budgetings
  end
  get 'get_branches' => 'finances/petty_cashes#get_branches', :as => :get_branches

  namespace :finances do
    resources :petty_cash
  end

  resources :product_details
  resources :transaction_histories do
    collection do
      get :search
    end
  end

  resources :ar_vouchers do
    collection do
      get :add_payment
    end
  end

  resources :products do
    collection do
      get :stock
      get :add_branch
      get :add_m_class
      get :autocomplete_goods_barcode
      get :mclass_per_department
      get :transaction_history
      post :import
    end
  end

  resources :change_barcodes

  resources :edc_bank_accounts do
    collection do
      post :import
    end
  end
  resources :edc_machines do
    collection do
      post :import
    end
  end
  resources :head_offices do
    collection do
      get :autocomplete_head_office_office_name
      post :import
    end
  end

  resources :branches do
    collection do
      get :autocomplete_branch_office_name
      post :import
    end
  end
  resources :vouchers
  resources :promos
  resources :stock_transfers do
    collection do
      get :search
      get :autocomplete_stock_transfer_name
      get :add_brand
      get :add_product
      get :get_last_number
    end
    member do
      get :print_to_pdf
    end
  end

  resources :units do
    collection do
      get :autocomplete_unit_name
      post :import
    end
  end

  resources :report_finances do
    collection do
      get :pembayaran_per_bulan
    end
  end

  resources :m_classes do
    collection do
      get :autocomplete_m_class_name
      get :add_sub_m_class
      post :import
    end
  end

  resources :product_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end

  resources :product_transfer_receipts do
    member do
      get :accept
      put :mark_as_received
      get :accept_product
    end
    collection do
      get :add_product
    end
  end
  resources :member_types do
    collection do
      get :autocomplete_member_type_name
      post :import
    end
  end
  resources :catalogs do
    collection do
      get :autocomplete_catalog_name
      post :import
    end
  end
  resources :petty_cash_types do
    collection do
      get :autocomplete_petty_cash_type_name
      post :import
    end
  end
  resources :colours do
    collection do
      get :autocomplete_colour_name
      post :import
    end
  end
  resources :cashbacks do
    collection do
      post :import
    end
  end
  resources :member_levels do
    collection do
      get :autocomplete_member_level_description
      post :import
    end
  end
  resources :to_do_lists do
    collection do
      post :import
    end
  end
  resources :promotions do
    collection do
      get :search
      get :autocomplete_promotion_name
      get :add_prize_list
      get :add_promo_item_list
      get :search_product_manual
      get :search_in_modal
      get :get_product
    end
  end

  resources :branch_prices

  resources :stock_opnames do
    collection do
      get :get_quantity_data
      get :start_stock_opname_data
      get :end_stock_opname_data
      get :select_stock_opname_data
    end
  end

  resources :stock_opname_details do
    collection do
      post :import
    end
  end

  resources :members do
    collection do
      get :search
      get :discount
      post :create_member_discount
      post :import
      get '/edit_member_discount/:id' => 'members#edit_member_discount', as: :edit_member_discount
      put '/update_member_discount/:id' => 'members#update_member_discount', as: :update_member_discount
      delete '/delete_member_discount/:id' => 'members#delete_member_discount', as: :delete_member_discount
      put '/expired/:id' => 'members#expire', as: :expire
      get '/setting_point' => 'members#setting_point', as: :setting_point
      post 'create_setting_point' => 'members#create_setting_point', as: :create_setting_point
    end
  end

  resources :colours do
    collection do
      get :search
      get :autocomplete_colour_name
    end
  end

  resources :out_stocks do
    collection do
      get :search
      get :autocomplete_out_stock_name
    end
  end

  resources :min_stocks do
    collection do
      get :search
      get :autocomplete_min_stock_name
    end
  end

  resources :price_histories do
    collection do
      get :search
    end
  end

  resources :good_transfers do
    member do
      get :print_to_pdf
    end
    collection do
      get :search
      get :autocomplete_good_transfer_code
      get :get_product
      get :add_brand
      get :add_product
      get :get_last_number
    end
  end

  resources :departments do
    collection do
      get :search
      get :autocomplete_department_name
      get :departments_per_supplier
      post :import
      get :departments_list
    end
  end

  resources :brands do
    collection do
      get :search
      get :autocomplete_brand_name
      post :import
      get :brands_per_supplier
      get :generate_data_brand
    end
  end

  resources :suppliers do
    collection do
      get :get_number
      get :search
      get :autocomplete_supplier_name
      get :autocomplete_supplier_code
      post :import
      get :add_contact
      get :add_bank_account
    end
  end

  resources :sizes do
    collection do
      get :search
      get :autocomplete_size_name
      get :generate_details
      post :import
    end
  end

  resources :types do
    collection do
      get :search
      get :autocomplete_type_name
      get 'detail_sub_type/:id' => "types#detail_sub_type", as: :detail_sub_type
      get 'new_sub_type/:id' => "types#new_sub_type", as: :new_sub_type
    end
  end

  devise_for :users
  resources :users do
    collection do
      get :autocomplete_name
    end
  end
  resources :user_profiles do

  end

  resources :organizations do
    member do
      get :position_edit
    end
    collection do
      get :search
      get :posisision_data
      get :position_index
      post :position_index
      get :position_show
      get :position_new
      post :position_create
      delete :position_destroy
      patch :position_update
      put :position_update

    end
  end

   resources :positions

  resources :fingerprints do
    collection do
      get :search
    end
  end

  resources :companies do
    collection do
      get :get_city
    end
  end

  resources :roles

  resources :approvals

  resources :asset_assignments do
    collection do
      post :return
    end
  end

  resources :recruitments

  resources :visions, only: [:index, :show] do
    collection do
      post :setup
      get :visi_misi
    end
  end

  resources :misions, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :cultures, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :code_of_conducts, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :values, only: [:index, :show] do
    collection do
      post :setup
    end
  end

  resources :holidays

  resources :personal_datas

  resources :holiday_types do
    collection do
      put :update_holiday_type
      get :search
    end
  end

  resources :shifts

app/models/product_mutation_history.rb
class ProductMutationHistory < ActiveRecord::Base
  belongs_to :product_detail
  belongs_to :product_mutation_detail
end

app/controllers/product_mutation_history_controller.rb
class ProductMutationHistoryController < ApplicationController
  def index
  	get_paginated_productmutationhistories
  	respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  def get_paginated_productmutationhistories
  	if params[:product_detail_id].blank?
      @productmutationhistories = ProductMutationHistory.all.paginate(page: params[:page], per_page: 100) || []
    else
      @productmutationhistories = ProductMutationHistory.where("product_detail_id = ?", params[:product_detail_id]).order(:id).paginate(page: params[:page], per_page: 100) || []
    end
    @product = ProductDetail.find_by_id(params[:product_detail_id]).product_size.product rescue nil
    @office = ProductDetail.find_by_id(params[:product_detail_id]).warehouse rescue nil
  end
end

app/controllers/productmutationhistory_controller.rb
class ProductmutationhistoryController < ApplicationController
end

app/helpers/product_mutation_history_helper.rb
module ProductMutationHistoryHelper
end

app/helpers/productmutationhistory_helper.rb
module ProductmutationhistoryHelper
end

app/views/product_mutation_history/_list_product_mutatin_history.html.erb
<% @productmutationhistories.each_with_index do |productmutationhistory, i| %>
  <tr>
    <td class="hidden-phone"><%= params[:page] ? (params[:page].to_i*10+i-9) : i+1 %></td>
    <td class="hidden-phone"><%= productmutationhistory.created_at.strftime('%d-%m-%Y') rescue '' %></td>
    <% if @product.blank? %>
      <td class="hidden-phone"><%= (link_to (productmutationhistory.product_detail.product_size.product.barcode), "/product_mutation_history/#{productmutationhistory.product_detail_id}") rescue '' %></td>
      <td class="hidden-phone"><%= (link_to ((productmutationhistory.product_detail.warehouse.office_name rescue nil)), "/product_mutation_history/#{productmutationhistory.product_detail_id}") %></td>
    <% end %>
    <td class="hidden-phone"><%= productmutationhistory.mutation_type %></td>
    <td class="hidden-phone"><%= productmutationhistory.quantity_type %></td>
    <td class="hidden-phone"><%= productmutationhistory.old_quantity.to_i %></td>
    <td class="hidden-phone"><%= productmutationhistory.moved_quantity %></td>
    <td class="hidden-phone"><%= productmutationhistory.new_quantity %></td>
  </tr>
<% end %>

<tr>
  <td colspan=10>
    <% if @productmutationhistories.present? %>
      <div class="dataTables_paginate paging_simple_numbers" id="dt_basic_paginate">
        <%= pagination_links(@productmutationhistories, options = {}) %>
      </div>
    <% else %>
      <%= raw '<center>No Data Available</center>' %>
    <% end %>
  </td>
</tr>

app/views/product_mutation_history/index.html.erb
<div id="ribbon">
  <ol class="breadcrumb">
   <li>
     <% if @product.present? %>
       <%= t(:product_mutation_history) %> </li><li><%= @product.barcode %> in <%= @office.office_name %>
     <% else %>
       <%= t(:product_mutation_history) %>
     <% end %>
  </li>
  </ol>
</div>
<div id="content">
  <section id="widget-grid" class="">
    <div id="notice_template"><%= render 'layouts/notice' %></div>
    <div class="row">
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget" id="wid-id-1" data-widget-editbutton="false"><!-- Widget ID (each widget will need unique ID)-->
          <h2 style="color:#BF1E2D; margin-top:-5px;">
            <i class="fa fa-list-ul"></i>
              <% if @product.present? %>
                <%= t(:mutation_history_for) %> <%= @product.barcode %> in <%= @office.office_name %>
              <% else %>
                <%= t(:product_mutation_history) %>
              <% end %>
          </h2> <!-- header content -->
          <div>
            <%= render 'shared/product_info', product: @product if @product.present? %>
            <table class="table table-striped table-bordered" width="100%">
              <thead>
                <tr>
                  <th>
                     No
                  </th>
                  <th>
                     Date
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'new_quantity-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'new_quantity-asc', class: 'sorting' %>
                    </span>
                    </th>
                   <% if @product.blank? %>
                      <th>
                         Barcode
                        <span style="float: right;">
                          <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'new_quantity-desc', class: 'sorting hide' %>
                          <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'new_quantity-asc', class: 'sorting' %>
                        </span>
                      </th>
                      <th>
                       Warehouse
                      <span style="float: right;">
                        <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'new_quantity-desc', class: 'sorting hide' %>
                        <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'new_quantity-asc', class: 'sorting' %>
                      </span>
                      </th>
                   <% end %>
                    <th> <%= t(:mutation_type) %>
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'mutation_type-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'cmutation_type-asc', class: 'sorting' %>
                        </span> </th>
                    <th> <%= t(:quantity_type) %>
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'quantity_type-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'quantity_type-asc', class: 'sorting' %>
                    </span> </th>
                    <th> <%= t(:old_quantity) %>
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'old_quantity-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'old_quantity-asc', class: 'sorting' %>
                    </span> </th>
                    <th> <%= t(:moved_quantity) %> 
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'moved_quantity-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'moved_quantity-asc', class: 'sorting' %>
                    </span></th>
                  <th>
                     <%= t(:new_quantity) %>
                    <span style="float: right;">
                      <%= link_to raw('<i class="fa fa-sort-desc"></i>'), 'javascript:void(0)', id: 'new_quantity-desc', class: 'sorting hide' %>
                      <%= link_to raw('<i class="fa fa-sort-asc"></i>'), 'javascript:void(0)', id: 'new_quantity-asc', class: 'sorting' %>
                    </span>
                    </th>
                  </tr>
                </thead>
                <tbody id='list_product-mutation-history'><%= render 'list_product_mutatin_history' %></tbody>
              </table>
            </div>
          </div>
      </article>
    </div>
  </section>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import Warna</h4>
      </div>
      <%= form_tag import_colours_path(:id => params[:id]), multipart: true do %>
        <div class="modal-body">
          <%= file_field_tag :file, accept: ".csv", onchange: "checkfile(this);" %>
        </div>
        <div class="modal-footer">
          <%= link_to "Download Template", colours_path(format: "csv", :a => "a"), :class => "btn btn-success" %>
          <%= submit_tag "Import", :class => "btn btn-primary", :id => 'commit'%>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  $('#commit').bind("click",function(){ 
    if(!$('#file').val()){
      alert("File belum dipilih");
      return false;
    }
  }); 
  window.reset = function (e) {
    e.wrap('<form>').closest('form').get(0).reset();
    e.unwrap();
  }
});
function checkfile(sender) {
    var validExts = new Array(".csv");
    var fileExt = sender.value;
    fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
    if (validExts.indexOf(fileExt) < 0) {
      alert("File ini bukan .csv");
      reset($("#file"));
      return false;
    }
    else return true;
};
</script>

app/views/product_mutation_history/index.js.erb
$("#list_product-mutation-history").html("<%= j(render 'list_product_mutatin_history') %>");
paging()